# Generated by Django 3.0.3 on 2020-03-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepredict', '0003_auto_20200318_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
